In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn import tree
import re
import seaborn as sns
%matplotlib inline


In [ ]:
data=pd.read_csv('/content/animals.csv',header='infer')

In [ ]:
data

Sr   Hair   Feathers   Eggs   Milk   Airborne   Aquatic   Predator  \
0    1      1          0      0      1          0         0          1   
1    2      1          0      0      1          0         0          0   
2    3      0          0      1      0          0         1          1   
3    4      1          0      0      1          0         0          1   
4    5      1          0      0      1          0         0          1   
..  ..    ...        ...    ...    ...        ...       ...        ...   
85  86      0          0      1      0          0         1          1   
86  87      0          0      1      0          0         1          1   
87  88      0          1      1      0          1         1          0   
88  89      0          0      1      0          0         0          0   
89  90      0          0      1      0          0         1          0   

     Teeth   Backbone   Breathes   Venemous   Fins   Legs   Tails   Domestic  \
0        1          1          1          0      0      4       0          0   
1        1          1          1          0      0      4       1          0   
2        1          1          0          0      1      0       1          0   
3        1          1          1          0      0      4       0          0   
4        1          1          1          0      0      4       1          0   
..     ...        ...        ...        ...    ...    ...     ...        ...   
85       0          0          0          0      0      5       0          0   
86       1          1          0          1      1      0       1          0   
87       0          1          1          0      0      2       1          0   
88       0          0          1          0      0      6       0          0   
89       1          1          1          0      0      4       0          0   

     Catsize  Class  
0          1      1  
1          1      1  
2          0      4  
3          1      1  
4          1      1  
..       ...    ...  
85         0      7  
86         1      4  
87         1      2  
88         0      6  
89         0      5  

[90 rows x 18 columns]

In [ ]:
# Prepare the data (features and target)
X = data.drop('Class', axis=1)  # Features
y = data['Class']               # Target (mammal or non-mammal)


In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [ ]:
X_train

Sr   Hair   Feathers   Eggs   Milk   Airborne   Aquatic   Predator  \
49  50      1          0      0      1          0         0          1   
62  63      0          0      1      0          0         0          1   
73  74      0          0      1      0          0         1          0   
69  70      1          0      0      1          0         0          1   
76  77      0          0      0      0          0         1          1   
..  ..    ...        ...    ...    ...        ...       ...        ...   
20  21      0          1      1      0          1         0          0   
60  61      0          0      1      0          0         1          1   
71  72      0          1      1      0          0         0          1   
14  15      0          0      1      0          0         1          1   
51  52      1          0      1      0          1         0          0   

     Teeth   Backbone   Breathes   Venemous   Fins   Legs   Tails   Domestic  \
49       1          1          1          0      0      4       1          0   
62       1          1          1          1      0      0       1          0   
73       1          1          0          0      1      0       1          0   
69       1          1          1          0      0      4       1          0   
76       1          1          0          1      0      0       1          0   
..     ...        ...        ...        ...    ...    ...     ...        ...   
20       0          1          1          0      0      2       1          1   
60       1          1          0          0      1      0       1          0   
71       0          1          1          0      0      2       1          0   
14       0          0          0          0      0      4       0          0   
51       0          0          1          0      0      6       0          0   

     Catsize  
49         0  
62         0  
73         0  
69         1  
76         0  
..       ...  
20         0  
60         1  
71         1  
14         0  
51         0  

[72 rows x 17 columns]

In [ ]:
X_test

Sr   Hair   Feathers   Eggs   Milk   Airborne   Aquatic   Predator  \
40  41      1          0      1      0          1         0          0   
22  23      1          0      0      1          0         0          0   
55  56      1          0      0      1          0         0          0   
70  71      1          0      0      1          0         0          0   
0    1      1          0      0      1          0         0          1   
26  27      0          0      1      0          0         1          1   
39  40      1          0      1      0          1         0          0   
65  66      1          0      0      1          0         0          0   
10  11      1          0      0      1          0         0          1   
44  45      1          0      0      1          0         0          1   
81  82      0          0      1      0          0         0          0   
35  36      1          0      0      1          0         0          0   
56  57      0          1      1      0          0         0          0   
86  87      0          0      1      0          0         1          1   
12  13      0          0      1      0          0         1          1   
4    5      1          0      0      1          0         0          1   
18  19      0          0      1      0          0         1          1   
28  29      1          0      0      1          0         0          0   

     Teeth   Backbone   Breathes   Venemous   Fins   Legs   Tails   Domestic  \
40       0          0          1          0      0      6       0          0   
22       1          1          1          0      0      4       1          0   
55       1          1          1          0      0      4       1          0   
70       1          1          1          0      0      4       1          1   
0        1          1          1          0      0      4       0          0   
26       1          1          1          1      0      4       0          0   
39       0          0          1          1      0      6       0          1   
65       1          1          1          0      0      4       1          1   
10       1          1          1          0      0      4       1          0   
44       1          1          1          0      0      4       1          0   
81       0          0          1          0      0      0       0          0   
35       1          1          1          0      0      4       1          1   
56       0          1          1          0      0      2       1          0   
86       1          1          0          1      1      0       1          0   
12       1          1          0          0      1      0       1          0   
4        1          1          1          0      0      4       1          0   
18       1          1          0          0      1      0       1          0   
28       1          1          1          0      0      4       1          0   

     Catsize  
40         0  
22         1  
55         1  
70         1  
0          1  
26         0  
39         0  
65         1  
10         1  
44         1  
81         0  
35         0  
56         1  
86         1  
12         0  
4          1  
18         1  
28         1

In [ ]:
# Initialize the model
clf = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)


In [ ]:
# Train the model
clf.fit(X_train, y_train)


DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [ ]:
import pydotplus

In [ ]:
from IPython.display import Image

In [ ]:
# Make predictions
y_pred = clf.predict(X_test)


In [25]:
# Get the unique class labels
unique_labels = set(y_test)

# Create target names for all unique labels
target_names = [f"Class {label}" for label in unique_labels]

# Generate and print the classification report
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=target_names))


Classification Report:
              precision    recall  f1-score   support

     Class 1       1.00      1.00      1.00        10
     Class 2       1.00      1.00      1.00         1
     Class 4       0.75      1.00      0.86         3
     Class 5       0.00      0.00      0.00         1
     Class 6       0.00      0.00      0.00         2
     Class 7       0.33      1.00      0.50         1

    accuracy                           0.83        18
   macro avg       0.51      0.67      0.56        18
weighted avg       0.75      0.83      0.78        18



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[10  0  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  0  0  2]
 [ 0  0  0  0  0  1]]


In [28]:
def classify_mammal(features):
    prediction = clf.predict([features])
    return 'Mammal' if prediction[0] == 1 else 'Non-Mammal'

In [30]:
# Example usage
new_entry = [1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 4, 1, 0, 1, 1]  # Replace with actual features
classification = classify_mammal(new_entry)
print(f"The classification for the new entry is: {classification}")

The classification for the new entry is: Non-Mammal


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
